### ISSUE TITLE
A new issue

### ISSUE THREAD

**Issue by StarshipSN20** [Ceriousyt/RVE2.0#2]
As the picture shows,
![20220217142226_1](https://user-images.githubusercontent.com/98255857/154431484-b3911bec-170a-4e1c-9cba-02afe33d89bd.jpg)
Do I have to send a log this time? Thanks!
P.S Hope the cloud desync problem being fixed soon. I've heard that this is due to the speeds of the cloud

**Comment by Ceriousyt** [comment]
There's no issue here, the citylights are supposed to look like this (due
to the mask), I would recommend launching from cape canaveral, one thing
you could try is pressing "apply" in the citylights window.

чт, 17 февр. 2022 г., 09:04 StarshipSN20 ***@***.***>:

**Comment by Ceriousyt** [comment]
Yes it's due to the speeds of the clouds, I haven't even tried fixing it
since there'll never be exact speeds.

чт, 17 февр. 2022 г., 09:04 StarshipSN20 ***@***.***>:

**Comment by Ceriousyt** [comment]
What version are you using? Rve2.0 v.1.0?

чт, 17 февр. 2022 г., 09:04 StarshipSN20 ***@***.***>:

**Comment by StarshipSN20** [comment]
Yes, it's the latest version
About the speed stuff, I've found that if the lower clouds are 15, then the medium should be 15.033, the higher should be 15.049. These are rough numbers though, and the clouds are still a little blurry, but it looks a lot better than the previous one

**Comment by Ceriousyt** [comment]
Thank you! Will try it out! How about the rest?

чт, 17 февр. 2022 г., 11:13 StarshipSN20 ***@***.***>:

**Comment by StarshipSN20** [comment]
It's great except for the framerate lol

**Comment by Ceriousyt** [comment]
> It's great except for the framerate lol

Lol, what fps do you have? I mean the Rtx 3070 mobile is not a weak card... It is possible that it runs out of vram, Ill release a 32k version in the future, for those with weaker hardware than mine. I have around 80 in LEO/MEO, 150-200 around all other planets.

**Comment by StarshipSN20** [comment]
Don't know why, but my fps seems quite low... Steam told me that I only got about 10fps in LEO. I've already installed the newest version of Geforce gameready, but it's still like that. i'm not an expert in computer, so I have no idea what's going on. I turned all the graphic options in ksp to the highest, is that the problem?

**Comment by Ceriousyt** [comment]
> Don't know why, but my fps seems quite low... Steam told me that I only got about 10fps in LEO. I've already installed the newest version of Geforce gameready, but it's still like that. i'm not an expert in computer, so I have no idea what's going on. I turned all the graphic options in ksp to the highest, is that the problem?

1. Have you forced directx 11?
2. Try opening he console and looking if there is anything sus going on, broken configs etc.
3. It could be a simple lack of vram, the mod eats 16gb of video memory for breakfast.

**Comment by Ceriousyt** [comment]
> Don't know why, but my fps seems quite low... Steam told me that I only got about 10fps in LEO. I've already installed the newest version of Geforce gameready, but it's still like that. i'm not an expert in computer, so I have no idea what's going on. I turned all the graphic options in ksp to the highest, is that the problem?

The reflections! have you turned them to max? I'm definitely not using max settings, more like medium and low on the reflections.

**Comment by StarshipSN20** [comment]
Ok, the reflections do reduce my framerate. Thanks for reminding! Now it looks much more fluent (actually 30fps is enough for me lol) 
I didn't forced dx11, and now I'm even struggling on how to install it :( I used Windows 10, and it seems that it is using dx12. I have no idea on how to force it. Is there a tutorial or something? Thanks

**Comment by StarshipSN20** [comment]
Forgot to say, my RAM is enough -- 32GB

**Comment by Ceriousyt** [comment]
Vram, the Frame buffer of your Gpu, 64k textures are not easy to render! If
you use TUFX, delete it and leave just ksp for a additional fps boost! Tufx
has bad performance even when disabled while Ks3p has virtually zero
performance impact. You could try my optional ks3p config on the release
page on github just replace the original one with it!

чт, 17 февр. 2022 г., 17:06 StarshipSN20 ***@***.***>:

**Comment by StarshipSN20** [comment]
Ok, it seems that I am already using dx11.
Thanks for the config, but what's the difference between the optional one and the original one?

**Comment by Ceriousyt** [comment]
The color gradation SHOULD change, seems like it didn't export correctly
that is a problem I still need to solve

пт, 18 февр. 2022 г., 08:40 StarshipSN20 ***@***.***>:

**Comment by Ceriousyt** [comment]
Remove KS3P, it seems to cause immense performance problems, youre better
off using TUFX. Tested on a low end rig, ate 60% of performance!

чт, 17 февр. 2022 г., 09:04 StarshipSN20 ***@***.***>:

**Comment by StarshipSN20** [comment]
So where do those cfg files goes? As far as I know TUFX as well as ks3p requires these files to work

**Comment by Ceriousyt** [comment]
You cannplace tham anywhere for TUFX, they have to be inside tha KS3P
folder to work

пт, 25 февр. 2022 г., 15:45 StarshipSN20 ***@***.***>:

**Comment by StarshipSN20** [comment]
Are there any planings for the next release at present?
